local kind = {
	[1]  = { "File"," "},
	[2]  = { "Module"," "},
	[3]  = { "Namespace"," "},
	[4]  = { "Package"," "},
	[5]  = { "Class"," "},
	[6]  = { "Method"," "},
	[7]  = { "Property"," "},
	[8]  = { "Field"," "},
	[9]  = { "Constructor"," "},
	[10] = { "Enum","了"},
	[11] = { "Interface","練"},
	[12] = { "Function"," "},
	[13] = { "Variable"," "},
	[14] = { "Constant"," "},
	[15] = { "String"," "},
	[16] = { "Number"," "},
	[17] = { "Boolean","◩ "},
	[18] = { "Array"," "},
	[19] = { "Object"," "},
	[20] = { "Key"," "},
	[21] = { "Null","ﳠ "},
	[22] = { "EnumMember"," "},
	[23] = { "Struct"," "},
	[24] = { "Event"," "},
	[25] = { "Operator"," "},
	[26] = { "TypeParameter"," "},
}

return kind
